### ISSUE TITLE
introduce camera settings (maybe) later

### ISSUE THREAD

**Issue by k-dominik** [oanegros/Blender_for_Biologists_2023#9]

**Comment by aafkegros** [comment]
Yes + multichannel first

**Comment by aafkegros** [comment]
When would you think camera settings should be introduced? @k-dominik 
One option is as lesson 1e, but then they're already busy making new render modes (v2m), other option is after multichannel, before v2m?

**Comment by aafkegros** [comment]
do lesson 1e camera, with keyframes.

**Comment by aafkegros** [comment]
fix in #14
